/**
 * System-wide Constants for the Privacy-Preserving Agentic Browser
 */

export const AgentState = Object.freeze({
  IDLE: 'IDLE',
  UNDERSTANDING_TASK: 'UNDERSTANDING_TASK',
  OBSERVING: 'OBSERVING',
  SANITIZING: 'SANITIZING',
  VISUAL_ANALYSIS: 'VISUAL_ANALYSIS',
  REASONING: 'REASONING',
  PLANNING: 'PLANNING',
  VALIDATING_ACTION: 'VALIDATING_ACTION',
  EXECUTING: 'EXECUTING',
  VERIFYING: 'VERIFYING',
  WAITING_FOR_USER: 'WAITING_FOR_USER',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
});

export const ActionType = Object.freeze({
  NAVIGATE: 'NAVIGATE',
  CLICK: 'CLICK',
  TYPE: 'TYPE',
  SELECT: 'SELECT',
  CHECK: 'CHECK',
  UNCHECK: 'UNCHECK',
  SCROLL: 'SCROLL',
  HOVER: 'HOVER',
  WAIT: 'WAIT',
  PRESS_KEY: 'PRESS_KEY',
  UPLOAD: 'UPLOAD',
  EXTRACT: 'EXTRACT',
  GO_BACK: 'GO_BACK',
  GO_FORWARD: 'GO_FORWARD',
  OPEN_TAB: 'OPEN_TAB',
  SWITCH_TAB: 'SWITCH_TAB',
  ASK_USER: 'ASK_USER',
  SUBMIT: 'SUBMIT',
  DONE: 'DONE'
});

export { MessageType } from './messages.js';

export const RiskLevel = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
});

export const SymbolicSecretSource = Object.freeze({
  LOCAL_AADHAAR: 'LOCAL_AADHAAR',
  LOCAL_PAN: 'LOCAL_PAN',
  LOCAL_FULL_NAME: 'LOCAL_FULL_NAME',
  LOCAL_DOB: 'LOCAL_DOB',
  LOCAL_PHONE: 'LOCAL_PHONE',
  LOCAL_EMAIL: 'LOCAL_EMAIL',
  LOCAL_ADDRESS: 'LOCAL_ADDRESS',
  LOCAL_PASSWORD: 'LOCAL_PASSWORD',
  LOCAL_DOCUMENT: 'LOCAL_DOCUMENT',
  LOCAL_CREDIT_CARD: 'LOCAL_CREDIT_CARD',
  LOCAL_CVV: 'LOCAL_CVV',
  LOCAL_PROFILE: 'LOCAL_PROFILE'
});

export const PIICategory = Object.freeze({
  AADHAAR: 'AADHAAR',
  PAN: 'PAN',
  PASSPORT: 'PASSPORT',
  PASSWORD: 'PASSWORD',
  OTP: 'OTP',
  CREDIT_CARD: 'CREDIT_CARD',
  CVV: 'CVV',
  BANK_ACCOUNT: 'BANK_ACCOUNT',
  PHONE: 'PHONE',
  EMAIL: 'EMAIL',
  DOB: 'DOB',
  FULL_NAME: 'FULL_NAME',
  ADDRESS: 'ADDRESS',
  DOCUMENT: 'DOCUMENT'
});

export const ServerDefaults = Object.freeze({
  BACKEND_BASE_URL: 'http://localhost:8000',
  VISION_ENDPOINT: '/vision',
  REASON_ENDPOINT: '/reason',
  MAX_STEPS_DEFAULT: 25,
  STABILITY_WAIT_MS: 400
});
