/**
 * System-wide Constants for the Privacy-Preserving Agentic Browser
 */

export const AgentState = Object.freeze({
  IDLE: 'IDLE',
  UNDERSTANDING_TASK: 'UNDERSTANDING_TASK',
  OBSERVING: 'OBSERVING',
  SANITIZING: 'SANITIZING',
  VISUAL_ANALYSIS: 'VISUAL_ANALYSIS',
  REASONING: 'REASONING',
  PLANNING: 'PLANNING',
  VALIDATING_ACTION: 'VALIDATING_ACTION',
  EXECUTING: 'EXECUTING',
  VERIFYING: 'VERIFYING',
  WAITING_FOR_USER: 'WAITING_FOR_USER',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
});

export const ActionType = Object.freeze({
  NAVIGATE: 'NAVIGATE',
  CLICK: 'CLICK',
  TYPE: 'TYPE',
  SELECT: 'SELECT',
  CHECK: 'CHECK',
  UNCHECK: 'UNCHECK',
  SCROLL: 'SCROLL',
  HOVER: 'HOVER',
  WAIT: 'WAIT',
  PRESS_KEY: 'PRESS_KEY',
  UPLOAD: 'UPLOAD',
  EXTRACT: 'EXTRACT',
  GO_BACK: 'GO_BACK',
  GO_FORWARD: 'GO_FORWARD',
  OPEN_TAB: 'OPEN_TAB',
  SWITCH_TAB: 'SWITCH_TAB',
  ASK_USER: 'ASK_USER',
  SUBMIT: 'SUBMIT',
  DONE: 'DONE',
  FILL_FORM_PLAN: 'FILL_FORM_PLAN'
});

export const MessageType = Object.freeze({
  START_TASK: 'START_TASK',
  PAUSE_TASK: 'PAUSE_TASK',
  RESUME_TASK: 'RESUME_TASK',
  CANCEL_TASK: 'CANCEL_TASK',
  USER_CONFIRM_ACTION: 'USER_CONFIRM_ACTION',
  USER_INPUT_REQUIRED: 'USER_INPUT_REQUIRED',
  USER_PROVIDE_INPUT: 'USER_PROVIDE_INPUT',
  GET_AGENT_STATUS: 'GET_AGENT_STATUS',
  AGENT_STATUS_UPDATE: 'AGENT_STATUS_UPDATE',
  PRIVACY_EVENT: 'PRIVACY_EVENT',
  UPDATE_VAULT: 'UPDATE_VAULT',
  GET_VAULT: 'GET_VAULT',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  EXTRACT_DOM: 'EXTRACT_DOM',
  EXTRACT_DOM_RESPONSE: 'EXTRACT_DOM_RESPONSE',
  EXECUTE_ACTION: 'EXECUTE_ACTION',
  EXECUTE_ACTION_RESPONSE: 'EXECUTE_ACTION_RESPONSE',
  HIGHLIGHT_ELEMENT: 'HIGHLIGHT_ELEMENT',
  SHOW_VISUAL_CURSOR: 'SHOW_VISUAL_CURSOR',
  CLEAR_OVERLAYS: 'CLEAR_OVERLAYS',
  CHECK_PAGE_STABILITY: 'CHECK_PAGE_STABILITY'
});

export const RiskLevel = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
});

export const SymbolicSecretSource = Object.freeze({
  LOCAL_AADHAAR: 'LOCAL_AADHAAR',
  LOCAL_PAN: 'LOCAL_PAN',
  LOCAL_FULL_NAME: 'LOCAL_FULL_NAME',
  LOCAL_DOB: 'LOCAL_DOB',
  LOCAL_PHONE: 'LOCAL_PHONE',
  LOCAL_EMAIL: 'LOCAL_EMAIL',
  LOCAL_ADDRESS: 'LOCAL_ADDRESS',
  LOCAL_CITY: 'LOCAL_CITY',
  LOCAL_STATE: 'LOCAL_STATE',
  LOCAL_ZIP: 'LOCAL_ZIP',
  LOCAL_PASSWORD: 'LOCAL_PASSWORD',
  LOCAL_DOCUMENT: 'LOCAL_DOCUMENT',
  LOCAL_CREDIT_CARD: 'LOCAL_CREDIT_CARD',
  LOCAL_CVV: 'LOCAL_CVV',
  LOCAL_PROFILE: 'LOCAL_PROFILE',
  LOCAL_COUNTRY: 'LOCAL_COUNTRY',
  LOCAL_GENDER: 'LOCAL_GENDER',
  LOCAL_TERMS: 'LOCAL_TERMS',
  LOCAL_SSN: 'LOCAL_SSN',
  LOCAL_SIN: 'LOCAL_SIN',
  LOCAL_NIN: 'LOCAL_NIN',
  LOCAL_NHS: 'LOCAL_NHS',
  LOCAL_IBAN: 'LOCAL_IBAN'
});

export const PIICategory = Object.freeze({
  AADHAAR: 'AADHAAR',
  PAN: 'PAN',
  PASSPORT: 'PASSPORT',
  PASSWORD: 'PASSWORD',
  OTP: 'OTP',
  CREDIT_CARD: 'CREDIT_CARD',
  CVV: 'CVV',
  BANK_ACCOUNT: 'BANK_ACCOUNT',
  PHONE: 'PHONE',
  EMAIL: 'EMAIL',
  DOB: 'DOB',
  FULL_NAME: 'FULL_NAME',
  ADDRESS: 'ADDRESS',
  DOCUMENT: 'DOCUMENT',
  SSN: 'SSN',
  SIN: 'SIN',
  NIN: 'NIN',
  NHS: 'NHS',
  IBAN: 'IBAN',
  IFSC: 'IFSC'
});

export const ServerDefaults = Object.freeze({
  BACKEND_BASE_URL: 'http://localhost:8000',
  VISION_ENDPOINT: '/vision',
  REASON_ENDPOINT: '/reason',
  MAX_STEPS_DEFAULT: 25,
  STABILITY_WAIT_MS: 400
});
